-- SpendLens Database Schema
-- Run this in your Supabase SQL Editor at:
-- https://supabase.com/dashboard -> SQL Editor

-- ============================================================
-- 1. AUDITS TABLE
-- Stores every audit result generated by the engine
-- ============================================================
CREATE TABLE IF NOT EXISTS audits (
  id TEXT PRIMARY KEY,                          -- nanoid(12) generated by the app
  results JSONB NOT NULL,                       -- Full AuditResult object
  tools JSONB,                                  -- Array of ToolAuditResult
  team_size INTEGER DEFAULT 1,
  use_case TEXT DEFAULT 'mixed',
  total_monthly_savings NUMERIC(10, 2) DEFAULT 0,
  total_annual_savings NUMERIC(10, 2) DEFAULT 0,
  total_credex_savings NUMERIC(10, 2) DEFAULT 0,
  savings_tier TEXT DEFAULT 'optimal',
  ai_summary TEXT,                              -- Gemini-generated summary (populated on demand)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Allow the service role to read/write (bypasses RLS)
ALTER TABLE audits ENABLE ROW LEVEL SECURITY;

-- Block all access by default (anon users cannot read or write)
CREATE POLICY "Block public access to audits"
  ON audits FOR ALL
  USING (false);

-- ============================================================
-- 2. LEADS TABLE
-- Stores user emails captured at the bottom of audit reports
-- ============================================================
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  audit_id TEXT REFERENCES audits(id) ON DELETE SET NULL,
  savings_tier TEXT DEFAULT 'unknown',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for leads
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Block all public access
CREATE POLICY "Block public access to leads"
  ON leads FOR ALL
  USING (false);
